export const columns = (t: any) => [
  {
    title: t("quota.table.company"),
    dataIndex: "company_name",
    key: "company_name",
    width: "20%",
    sorter: true,
  },
  {
    title: t("quota.table.vendor"),
    dataIndex: "vendor_name",
    key: "vendor_name",
    width: "20%",
    sorter: true,
  },
  {
    title: t("quota.table.product"),
    dataIndex: "product_name",
    key: "product_name",
    width: "20%",
    sorter: true,
  },
  {
    title: t("quota.table.quantity"),
    dataIndex: "qty",
    key: "qty",
    width: "10%",
    sorter: true,
    align: "center" as const,
  },
  {
    title: t("quota.table.year"),
    dataIndex: "year",
    key: "year",
    width: "10%",
    sorter: true,
    align: "center" as const,
  },
  {
    title: t("quota.table.createdAt"),
    dataIndex: "created_at",
    key: "created_at",
    width: "10%",
    sorter: true,
  },
  {
    title: t("quota.table.updatedAt"),
    dataIndex: "updated_at",
    key: "updated_at",
    width: "10%",
    sorter: true,
  },
  {
    title: t("common.actions"),
    key: "actions",
    width: "10%",
    align: "center" as const,
    fixed: "right" as const,
  },
];